apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
    name: rails-blog-db
spec:
    name: rails-blog
    owner: rails-blog-user
    cluster:
        name: default-cluster
    ensure: present
