# IngressRoute Backend
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
    name: rails-blog-ingressroute
    namespace: default
spec:
    entryPoints:
        - websecure
    routes:
        - match: Host(`blog.titanforgesystems.com.br`) && PathPrefix(`/`)
          kind: Rule
          services:
              - name: rails-blog-service
                port: 80
    tls:
        certResolver: le
